// frontend/src/pages/ForYou.tsx
import { useCallback, useEffect, useState } from 'react';
import { Sparkles, ExternalLink, RefreshCw } from 'lucide-react';
import MediaThumb from '@/lib/components/MediaThumb';
import SectionHeading from '@/lib/components/SectionHeading';
import PlaylistModal from '@/lib/components/PlaylistModal';
import {
	recommendations,
	previewPlaylist,
	createPlaylist,
	type Recommendations,
	type RecPlaylist,
	type ProposedPlaylist,
	type StatsRangeValue
} from '@/lib/data/music';
import styles from './ForYou.module.css';

const lengthOptions = [10, 15, 25, 40, 50];

const rowSkeletons = Array.from({ length: 3 }, (_, i) => i);
const cardSkeletons = Array.from({ length: 6 }, (_, i) => i);

// Per-shelf save state, keyed by playlist.key — each row saves independently.
type SaveState = { status: 'saving' | 'saved' | 'error'; url?: string | null; error?: string };

// Page contract props (unused here, but App passes them to every page).
type ForYouProps = {
	activeRange?: StatsRangeValue;
	onRangeChange?: (range: StatsRangeValue) => void;
	loading?: boolean;
};

export default function ForYou(_props: ForYouProps) {
	const [instruction, setInstruction] = useState('');
	const [length, setLength] = useState(25);
	const [describeError, setDescribeError] = useState('');

	const [feed, setFeed] = useState<Recommendations | null>(null);
	const [feedStatus, setFeedStatus] = useState<'loading' | 'ready' | 'error'>('loading');
	const [refreshing, setRefreshing] = useState(false);

	const [modalOpen, setModalOpen] = useState(false);
	const [modalLoading, setModalLoading] = useState(false);
	const [modalPlaylist, setModalPlaylist] = useState<ProposedPlaylist | RecPlaylist | null>(null);

	const [saveStates, setSaveStates] = useState<Record<string, SaveState>>({});

	const loadFeed = useCallback(async (refresh = false) => {
		// On refresh keep the current feed visible and just spin the button; only the
		// first (cold) load shows the full skeletons.
		if (refresh) setRefreshing(true);
		else setFeedStatus('loading');
		try {
			setFeed(await recommendations(refresh));
			// Keys are stable across rebuilds but their tracks are not, so a stale
			// "Open in Spotify" would point at the wrong playlist.
			setSaveStates({});
			setFeedStatus('ready');
		} catch {
			if (!refresh) setFeedStatus('error');
		} finally {
			setRefreshing(false);
		}
	}, []);

	useEffect(() => {
		void loadFeed();
	}, [loadFeed]);

	async function describe() {
		const text = instruction.trim();
		if (!text) return;
		setDescribeError('');
		setModalPlaylist(null);
		setModalLoading(true);
		setModalOpen(true);
		try {
			setModalPlaylist(await previewPlaylist({ instruction: text, length }));
		} catch (error) {
			setModalOpen(false);
			setDescribeError(error instanceof Error ? error.message : 'Could not build a playlist.');
		} finally {
			setModalLoading(false);
		}
	}

	async function saveRow(playlist: RecPlaylist) {
		if (saveStates[playlist.key]?.status === 'saving') return;
		setSaveStates((states) => ({ ...states, [playlist.key]: { status: 'saving' } }));
		try {
			const result = await createPlaylist({
				name: playlist.name,
				description: playlist.description,
				trackUris: playlist.trackUris,
				isPublic: false
			});
			setSaveStates((states) => ({
				...states,
				[playlist.key]: { status: 'saved', url: result.spotifyUrl }
			}));
		} catch (error) {
			setSaveStates((states) => ({
				...states,
				[playlist.key]: {
					status: 'error',
					error: error instanceof Error ? error.message : 'Could not save to Spotify.'
				}
			}));
		}
	}

	return (
		<>
			<section className={styles.pageHeader}>
				<SectionHeading title="For You" subtitle="New music, picked from what you love." />
				<button
					type="button"
					className={styles.refresh}
					onClick={() => loadFeed(true)}
					disabled={refreshing || feedStatus === 'loading'}
					title="Rebuild your feed with fresh picks"
				>
					<RefreshCw size={16} strokeWidth={2.2} className={refreshing ? 'spin' : undefined} />
					{refreshing ? 'Refreshing…' : 'Refresh'}
				</button>
			</section>

			{/* AI describe bar */}
			<form
				className={styles.describe}
				onSubmit={(event) => {
					event.preventDefault();
					void describe();
				}}
			>
				<div className={styles.describeField}>
					<Sparkles size={20} strokeWidth={2.2} className={styles.describeIcon} />
					<input
						type="text"
						value={instruction}
						onChange={(event) => setInstruction(event.target.value)}
						placeholder="Describe what you want to hear — “late-night drive, moody synths”"
						aria-label="Describe what you want to hear"
					/>
					<select
						value={length}
						onChange={(event) => setLength(Number(event.target.value))}
						aria-label="Playlist length"
						className={styles.length}
					>
						{lengthOptions.map((option) => (
							<option key={option} value={option}>
								{option} tracks
							</option>
						))}
					</select>
					<button type="submit" className={styles.go} disabled={!instruction.trim()}>
						Create
					</button>
				</div>
				{describeError && <p className={styles.error}>{describeError}</p>}
			</form>

			{/* Feed */}
			{feedStatus === 'loading' ? (
				<div className={styles.feed}>
					{rowSkeletons.map((row) => (
						<section key={row} className={styles.shelf}>
							<span className={`skeleton ${styles.skelHeading}`}></span>
							<div className={styles.rail}>
								{cardSkeletons.map((card) => (
									<article key={card} className={`${styles.song} ${styles.skeletonCard}`}>
										<span className={`skeleton ${styles.skelArt}`}></span>
										<span className={`skeleton ${styles.skelLine}`} style={{ width: '80%' }}></span>
										<span className={`skeleton ${styles.skelLine}`} style={{ width: '55%' }}></span>
									</article>
								))}
							</div>
						</section>
					))}
				</div>
			) : feedStatus === 'error' ? (
				<div className={styles.notice}>
					<p>Couldn’t load your recommendations.</p>
					<button type="button" className={styles.ghost} onClick={() => loadFeed()}>
						<RefreshCw size={16} strokeWidth={2.2} /> Try again
					</button>
				</div>
			) : feed ? (
				<div className={styles.feed}>
					{feed.playlists.map((playlist) => {
						const save = saveStates[playlist.key];
						return (
							<section key={playlist.key} className={styles.shelf}>
								<header className={styles.shelfHead}>
									<div className={styles.shelfTitle}>
										<h2>{playlist.name}</h2>
										<small>
											{playlist.description} · {playlist.tracks.length} tracks
										</small>
									</div>
									{save?.status === 'saved' && save.url ? (
										<a
											className={styles.save}
											href={save.url}
											target="_blank"
											rel="noreferrer noopener"
										>
											<ExternalLink size={15} strokeWidth={2.2} /> Open in Spotify
										</a>
									) : (
										<button
											type="button"
											className={styles.save}
											onClick={() => saveRow(playlist)}
											disabled={save?.status === 'saving'}
										>
											{save?.status === 'saving' ? 'Saving…' : 'Save as playlist'}
										</button>
									)}
								</header>
								{save?.status === 'error' && <p className={styles.error}>{save.error}</p>}
								<div className={styles.rail}>
									{playlist.tracks.map((track, index) => (
										<article key={track.spotifyTrackId ?? index} className={styles.song}>
											<MediaThumb
												kind="cover"
												src={track.coverUrl}
												alt={`${track.album} artwork`}
												size="large"
												label={track.title}
											/>
											<strong>{track.title}</strong>
											<small>{track.artist}</small>
											{track.externalUrl && (
												<a
													className={styles.open}
													href={track.externalUrl}
													target="_blank"
													rel="noreferrer noopener"
													aria-label={`Open ${track.title} in Spotify`}
												>
													<ExternalLink size={16} strokeWidth={2.2} />
												</a>
											)}
										</article>
									))}
								</div>
							</section>
						);
					})}

					{!feed.playlists.length && (
						<div className={styles.notice}>
							<p>Sync your Spotify library to get recommendations.</p>
						</div>
					)}
				</div>
			) : null}

			<PlaylistModal
				open={modalOpen}
				loading={modalLoading}
				playlist={modalPlaylist}
				onClose={() => setModalOpen(false)}
			/>
		</>
	);
}

// frontend/src/pages/ForYou.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { Sparkles, ExternalLink, RefreshCw } from '@lucide/svelte';
	import MediaThumb from '$lib/components/MediaThumb.svelte';
	import SectionHeading from '$lib/components/SectionHeading.svelte';
	import PlaylistModal from '$lib/components/PlaylistModal.svelte';
	import {
		recommendations,
		previewPlaylist,
		createPlaylist,
		type Recommendations,
		type RecPlaylist,
		type ProposedPlaylist,
		type StatsRangeValue
	} from '$lib/data/music';

	// Page contract props (unused here, but App passes them to every page).
	let {}: {
		activeRange?: StatsRangeValue;
		onRangeChange?: (range: StatsRangeValue) => void;
		loading?: boolean;
	} = $props();

	const lengthOptions = [10, 15, 25, 40, 50];

	let instruction = $state('');
	let length = $state(25);
	let describeError = $state('');

	let feed = $state<Recommendations | null>(null);
	let feedStatus = $state<'loading' | 'ready' | 'error'>('loading');
	let refreshing = $state(false);

	let modalOpen = $state(false);
	let modalLoading = $state(false);
	let modalPlaylist = $state<ProposedPlaylist | RecPlaylist | null>(null);

	const rowSkeletons = Array.from({ length: 3 }, (_, i) => i);
	const cardSkeletons = Array.from({ length: 6 }, (_, i) => i);

	onMount(loadFeed);

	async function loadFeed(refresh = false) {
		// On refresh keep the current feed visible and just spin the button; only the
		// first (cold) load shows the full skeletons.
		if (refresh) refreshing = true;
		else feedStatus = 'loading';
		try {
			feed = await recommendations(refresh);
			// Keys are stable across rebuilds but their tracks are not, so a stale
			// "Open in Spotify" would point at the wrong playlist.
			saveStates = {};
			feedStatus = 'ready';
		} catch {
			if (!refresh) feedStatus = 'error';
		} finally {
			refreshing = false;
		}
	}

	async function describe() {
		const text = instruction.trim();
		if (!text) return;
		describeError = '';
		modalPlaylist = null;
		modalLoading = true;
		modalOpen = true;
		try {
			modalPlaylist = await previewPlaylist({ mode: 'instruction', instruction: text, length });
		} catch (error) {
			modalOpen = false;
			describeError = error instanceof Error ? error.message : 'Could not build a playlist.';
		} finally {
			modalLoading = false;
		}
	}

	// Per-shelf save state, keyed by playlist.key — each row saves independently.
	type SaveState = { status: 'saving' | 'saved' | 'error'; url?: string | null; error?: string };
	let saveStates = $state<Record<string, SaveState>>({});

	async function saveRow(playlist: RecPlaylist) {
		if (saveStates[playlist.key]?.status === 'saving') return;
		saveStates[playlist.key] = { status: 'saving' };
		try {
			const result = await createPlaylist({
				name: playlist.name,
				description: playlist.description,
				trackUris: playlist.trackUris,
				isPublic: false
			});
			saveStates[playlist.key] = { status: 'saved', url: result.spotifyUrl };
		} catch (error) {
			saveStates[playlist.key] = {
				status: 'error',
				error: error instanceof Error ? error.message : 'Could not save to Spotify.'
			};
		}
	}
</script>

<section class="page-header">
	<SectionHeading title="For You" subtitle="New music, picked from what you love." />
	<button
		type="button"
		class="refresh"
		onclick={() => loadFeed(true)}
		disabled={refreshing || feedStatus === 'loading'}
		title="Rebuild your feed with fresh picks"
	>
		<RefreshCw size={16} strokeWidth={2.2} class={refreshing ? 'spin' : undefined} />
		{refreshing ? 'Refreshing…' : 'Refresh'}
	</button>
</section>

<!-- AI describe bar -->
<form
	class="describe"
	onsubmit={(event) => {
		event.preventDefault();
		describe();
	}}
>
	<div class="describe-field">
		<Sparkles size={20} strokeWidth={2.2} class="describe-icon" />
		<input
			type="text"
			bind:value={instruction}
			placeholder="Describe what you want to hear — “late-night drive, moody synths”"
			aria-label="Describe what you want to hear"
		/>
		<select bind:value={length} aria-label="Playlist length" class="length">
			{#each lengthOptions as option (option)}
				<option value={option}>{option} tracks</option>
			{/each}
		</select>
		<button type="submit" class="go" disabled={!instruction.trim()}>Create</button>
	</div>
	{#if describeError}<p class="error">{describeError}</p>{/if}
</form>

<!-- Feed -->
{#if feedStatus === 'loading'}
	<div class="feed">
		{#each rowSkeletons as row (row)}
			<section class="shelf">
				<span class="skeleton skel-heading"></span>
				<div class="rail">
					{#each cardSkeletons as card (card)}
						<article class="song skeleton-card">
							<span class="skeleton skel-art"></span>
							<span class="skeleton skel-line" style="width:80%"></span>
							<span class="skeleton skel-line" style="width:55%"></span>
						</article>
					{/each}
				</div>
			</section>
		{/each}
	</div>
{:else if feedStatus === 'error'}
	<div class="notice">
		<p>Couldn’t load your recommendations.</p>
		<button type="button" class="ghost" onclick={() => loadFeed()}>
			<RefreshCw size={16} strokeWidth={2.2} /> Try again
		</button>
	</div>
{:else if feed}
	<div class="feed">
		{#each feed.playlists as playlist (playlist.key)}
			{@const save = saveStates[playlist.key]}
			<section class="shelf">
				<header class="shelf-head">
					<div class="shelf-title">
						<h2>{playlist.name}</h2>
						<small>{playlist.description} · {playlist.tracks.length} tracks</small>
					</div>
					{#if save?.status === 'saved' && save.url}
						<a class="save" href={save.url} target="_blank" rel="noreferrer noopener">
							<ExternalLink size={15} strokeWidth={2.2} /> Open in Spotify
						</a>
					{:else}
						<button
							type="button"
							class="save"
							onclick={() => saveRow(playlist)}
							disabled={save?.status === 'saving'}
						>
							{save?.status === 'saving' ? 'Saving…' : 'Save as playlist'}
						</button>
					{/if}
				</header>
				{#if save?.status === 'error'}<p class="error">{save.error}</p>{/if}
				<div class="rail">
					{#each playlist.tracks as track, index (track.spotifyTrackId ?? index)}
						<article class="song">
							<MediaThumb
								kind="cover"
								src={track.coverUrl}
								alt={`${track.album} artwork`}
								size="large"
								label={track.title}
							/>
							<strong>{track.title}</strong>
							<small>{track.artist}</small>
							{#if track.externalUrl}
								<a
									class="open"
									href={track.externalUrl}
									target="_blank"
									rel="noreferrer noopener"
									aria-label={`Open ${track.title} in Spotify`}
								>
									<ExternalLink size={16} strokeWidth={2.2} />
								</a>
							{/if}
						</article>
					{/each}
				</div>
			</section>
		{/each}

		{#if !feed.playlists.length}
			<div class="notice">
				<p>Sync your Spotify library to get recommendations.</p>
			</div>
		{/if}
	</div>
{/if}

<PlaylistModal
	open={modalOpen}
	loading={modalLoading}
	playlist={modalPlaylist}
	onClose={() => (modalOpen = false)}
/>

<style>
	.page-header {
		display: flex;
		align-items: end;
		justify-content: space-between;
		gap: 16px;
		margin-bottom: 20px;
	}

	.refresh {
		display: inline-flex;
		align-items: center;
		gap: 8px;
		min-height: 38px;
		padding: 0 16px;
		border: 1px solid var(--color-border);
		border-radius: 999px;
		background: transparent;
		color: var(--color-soft);
		font-weight: 700;
		font-size: 0.86rem;
		cursor: pointer;
		flex: 0 0 auto;
		transition:
			background 160ms ease,
			color 160ms ease;
	}

	.refresh:hover:not(:disabled) {
		background: #1f1f1f;
		color: #fff;
	}

	.refresh:disabled {
		opacity: 0.55;
		cursor: progress;
	}

	/* describe bar */
	.describe {
		margin-bottom: 34px;
	}

	.describe-field {
		display: flex;
		align-items: center;
		gap: 10px;
		padding: 8px 8px 8px 16px;
		border: 1px solid var(--color-border);
		border-radius: 999px;
		background: var(--color-surface-elevated);
		transition: border-color 160ms ease;
	}

	.describe-field:focus-within {
		border-color: var(--color-accent);
	}

	.describe-field :global(.describe-icon) {
		color: var(--color-accent);
		flex: 0 0 auto;
	}

	.describe-field input {
		flex: 1 1 auto;
		min-width: 0;
		border: 0;
		background: transparent;
		color: #fff;
		font: inherit;
		font-size: 1rem;
		padding: 8px 0;
	}

	.describe-field input:focus {
		outline: none;
	}

	.length {
		flex: 0 0 auto;
		border: 1px solid var(--color-border);
		border-radius: 999px;
		background: #121212;
		color: var(--color-soft);
		font: inherit;
		font-size: 0.82rem;
		padding: 8px 10px;
		cursor: pointer;
	}

	.go {
		flex: 0 0 auto;
		min-height: 42px;
		padding: 0 22px;
		border: 0;
		border-radius: 999px;
		background: var(--color-accent);
		color: #061109;
		font-weight: 800;
		cursor: pointer;
		transition: transform 160ms ease;
	}

	.go:hover:not(:disabled) {
		transform: translateY(-1px);
	}

	.go:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.error {
		margin: 12px 4px 0;
		color: #ffd2d2;
		font-size: 0.85rem;
	}

	/* feed */
	.feed {
		display: grid;
		gap: 34px;
	}

	.shelf-head {
		display: flex;
		align-items: end;
		justify-content: space-between;
		gap: 16px;
		margin: 0 0 14px;
	}

	.shelf h2 {
		margin: 0;
		font-size: 1.3rem;
	}

	.shelf-title small {
		display: block;
		margin-top: 4px;
		color: #a7a7a7;
		font-size: 0.82rem;
	}

	.save {
		display: inline-flex;
		align-items: center;
		gap: 7px;
		flex: none;
		padding: 8px 16px;
		border: 1px solid var(--color-border);
		border-radius: 999px;
		background: transparent;
		color: #fff;
		font-size: 0.85rem;
		font-weight: 600;
		cursor: pointer;
		transition:
			background 160ms ease,
			border-color 160ms ease,
			color 160ms ease;
	}

	.save:hover:not(:disabled) {
		border-color: #1ed760;
		background: #1ed760;
		color: #071108;
	}

	.save:disabled {
		opacity: 0.6;
		cursor: default;
	}

	.rail {
		display: flex;
		gap: 16px;
		overflow-x: auto;
		padding-bottom: 10px;
		scrollbar-width: thin;
	}

	.song {
		position: relative;
		display: grid;
		align-content: start;
		gap: 4px;
		flex: 0 0 168px;
		width: 168px;
		padding: 12px;
		border-radius: 10px;
		background: #181818;
		transition: background 160ms ease;
	}

	.song:hover {
		background: #242424;
	}

	.song strong,
	.song small {
		min-width: 0;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.song strong {
		margin-top: 8px;
		font-size: 0.92rem;
	}

	.song small {
		color: #a7a7a7;
		font-size: 0.82rem;
	}

	.open {
		position: absolute;
		right: 18px;
		top: 18px;
		display: grid;
		width: 32px;
		height: 32px;
		place-items: center;
		border-radius: 999px;
		background: rgba(0, 0, 0, 0.5);
		color: #fff;
		opacity: 0;
		transition: opacity 160ms ease;
	}

	.song:hover .open {
		opacity: 1;
	}

	.open:hover {
		background: #1ed760;
		color: #071108;
	}

	/* states */
	.notice {
		display: grid;
		place-items: center;
		gap: 14px;
		padding: 56px 24px;
		border: 1px dashed var(--color-border);
		border-radius: 12px;
		color: var(--color-muted);
		text-align: center;
	}

	.ghost {
		display: inline-flex;
		align-items: center;
		gap: 8px;
		min-height: 40px;
		padding: 0 18px;
		border: 0;
		border-radius: 999px;
		background: #2a2a2a;
		color: #fff;
		font-weight: 800;
		cursor: pointer;
	}

	.skel-heading {
		display: block;
		width: 180px;
		height: 20px;
		margin-bottom: 14px;
		border-radius: 6px;
	}

	.skeleton-card {
		pointer-events: none;
	}

	.skel-art {
		width: 100%;
		aspect-ratio: 1;
		border-radius: 8px;
		margin-bottom: 8px;
	}

	.skel-line {
		height: 11px;
		border-radius: 4px;
	}

	@media (max-width: 640px) {
		.describe-field {
			flex-wrap: wrap;
			border-radius: 16px;
		}

		.describe-field input {
			flex-basis: 100%;
			order: -1;
		}
	}
</style>
